### ISSUE TITLE
undefined method `cattr_accessor' for OpenApi::Config:Module (NoMethodError)

### ISSUE THREAD

**Issue by werdlerk** [zhandao/zero-rails_openapi#31]
Hello,

I'm trying to get zero-rails_openapi gem working on my Rails 3.2 project for generating nice OpenAPI documentation.

Unfortunately, I get the following error when trying to start the application (or console) after installation of the gem:

    /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/config.rb:9:in `<module:Config>': undefined method `cattr_accessor' for OpenApi::Config:Module (NoMethodError)
    Did you mean?  mattr_accessor
                  attr_accessor
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/config.rb:5:in `<module:OpenApi>'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/config.rb:4:in `<top (required)>'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api.rb:2:in `<top (required)>'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
      from /Users/kwerdler/projects/blank-3.2.22.5/config/initializers/open_api.rb:2:in `<top (required)>'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `load'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `block in load'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:245:in `load'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/engine.rb:592:in `each'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/engine.rb:592:in `block in <class:Engine>'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `instance_exec'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `run'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/initializable.rb:55:in `block in run_initializers'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `each'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `run_initializers'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/application.rb:136:in `initialize!'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
      from /Users/kwerdler/projects/blank-3.2.22.5/config/environment.rb:5:in `<top (required)>'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/application.rb:103:in `require'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/application.rb:103:in `require_environment!'
      from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands.rb:40:in `<top (required)>'
      from script/rails:6:in `require'
      from script/rails:6:in `<main>'
  
To make sure this wasn't caused by anything special in the project, I tried again with a freshly generated Rails **3.2.22.5** application by using Ruby **2.3.3**p222 (2016-11-21 revision 56859) [x86_64-darwin17]. Unfortunately this yielded the same result.

Is there some incompatibility I'm not aware of? Please advise me.

Thanks in advance.

**Comment by zhandao** [comment]
Hi, the method `cattr_accessor` used to be for Class in [activesupport 3.2](https://github.com/rails/rails/blob/3-2-stable/activesupport/lib/active_support/core_ext/class/attribute_accessors.rb).

After [activesupport 4.1](https://github.com/rails/rails/blob/4-1-stable/activesupport/lib/active_support/core_ext/module/attribute_accessors.rb), `cattr_accessor` is for `Module`.

I'll consider changing it to `attr_accessor` in the next version. But if you want to solve the problem temporarily, make a monkey patch like this:
```ruby
module OpenApi
  module Config
    def self.cattr_accessor; mattr_accessor end
  end
end
```

**Comment by werdlerk** [comment]
Thanks, @zhandao . 

I've added the following to the very top of my open_api.rb initializer file:
```ruby
module OpenApi
  module Config
    def self.cattr_accessor(attr); mattr_accessor(attr) end
  end
  def self.cattr_accessor(attr); mattr_accessor(attr) end
end
```

As you can see, I had to put another method in there as it was also complaining about the OpenApi module not having the `cattr_accessor` method.

Unfortunately when trying to run the `OpenApi.write_docs` command, I get the following error:
```
LoadError: cannot load such file -- action_dispatch/routing/inspector
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:234:in `block in load_dependency'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:639:in `new_constants_in'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:234:in `load_dependency'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:79:in `routes'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:87:in `routes_list'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/dsl.rb:69:in `ctrl_routes_list'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/dsl.rb:41:in `api'
	from /Users/kwerdler/projects/blank-3.2.22.5/app/controllers/api/examples_controller.rb:2:in `<class:ExamplesController>'
	from /Users/kwerdler/projects/blank-3.2.22.5/app/controllers/api/examples_controller.rb:1:in `<top (required)>'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:469:in `load'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:469:in `block in load_file'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:639:in `new_constants_in'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:468:in `load_file'
... 3 levels...
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:190:in `each'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:190:in `const_missing'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/inflector/methods.rb:230:in `block in constantize'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/inflector/methods.rb:229:in `each'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/inflector/methods.rb:229:in `constantize'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/string/inflections.rb:54:in `constantize'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:19:in `block in generate_docs'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:18:in `each'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:18:in `generate_docs'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:54:in `write_docs'
	from (irb):1
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:47:in `start'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:8:in `start'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

Do you know what the problem is here?

**Comment by werdlerk** [comment]
Ok, so I did the following command:
```
rake routes >> config/api_routes.txt
```
which saved the following into the text file:
```
          posts GET    /posts(.:format)           posts#index
                POST   /posts(.:format)           posts#create
       new_post GET    /posts/new(.:format)       posts#new
      edit_post GET    /posts/:id/edit(.:format)  posts#edit
           post GET    /posts/:id(.:format)       posts#show
                PUT    /posts/:id(.:format)       posts#update
                DELETE /posts/:id(.:format)       posts#destroy
greetings_hello GET    /greetings/hello(.:format) greetings#hello
      api_index GET    /api(.:format)             api#index
                POST   /api(.:format)             api#create
        new_api GET    /api/new(.:format)         api#new
       edit_api GET    /api/:id/edit(.:format)    api#edit
            api GET    /api/:id(.:format)         api#show
                PUT    /api/:id(.:format)         api#update
                DELETE /api/:id(.:format)         api#destroy
```

I set the configuration as you advised. Upon another retry of running the `OpenApi.write_docs` command, the following error was given:
```
NoMethodError: undefined method `match?' for "                POST   /posts(.:format)           posts#create":String
Did you mean?  match
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:88:in `block in routes_list'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:87:in `map'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:87:in `routes_list'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/dsl.rb:69:in `ctrl_routes_list'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/dsl.rb:41:in `api'
	from /Users/kwerdler/projects/blank-3.2.22.5/app/controllers/api/examples_controller.rb:2:in `<class:ExamplesController>'
	from /Users/kwerdler/projects/blank-3.2.22.5/app/controllers/api/examples_controller.rb:1:in `<top (required)>'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:469:in `load'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:469:in `block in load_file'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:639:in `new_constants_in'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:468:in `load_file'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:353:in `require_or_load'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:502:in `load_missing_constant'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:192:in `block in const_missing'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:190:in `each'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:190:in `const_missing'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/inflector/methods.rb:230:in `block in constantize'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/inflector/methods.rb:229:in `each'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/inflector/methods.rb:229:in `constantize'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/string/inflections.rb:54:in `constantize'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:19:in `block in generate_docs'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:18:in `each'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:18:in `generate_docs'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zero-rails_openapi-1.6.1/lib/open_api/generator.rb:54:in `write_docs'
	from (irb):1
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:47:in `start'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:8:in `start'
	from /Users/kwerdler/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-3.2.22.5/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

Thank you for your help but I'm going to stop trying to use this gem. This is becoming way too hacky for us to use. I'll probably try to write the YAML file myself using the Swagger Editor.

**Comment by zhandao** [comment]
I'm sorry. I hope you will try it again in the latest version of Ruby&Rails.
