### ISSUE TITLE
The server will not start after upgrading to version 2.0.1

### ISSUE THREAD

**Issue by akram71093** [zhandao/zero-rails_openapi#37]
I got the following error when trying to start the server.
gems/zero-rails_openapi-2.0.1/lib/open_api/config_dsl.rb:12:in `open_api': undefined method `[]=' for nil:NilClass (NoMethodError)

The same code works with version 1.7.0

**Comment by zhandao** [comment]
What's your Rails version?

**Comment by zhandao** [comment]
Please try the latest commit from github:
`gem 'zero-rails_openapi', github: 'zhandao/zero-rails_openapi'`
@akram71093

**Comment by drjonnicholson** [comment]
I have the same problem with 2.0.2, stack trace indicates the issue is at https://github.com/zhandao/zero-rails_openapi/blob/master/lib/open_api.rb#L47

Should it be `OpenApi.docs` or `Config.docs[doc_name]` like in the other methods?

**Comment by zhandao** [comment]
@akram71093 @drjonnicholson Oh sorry.

The problem is caused by passing parameter default to `cattr_accessor` (ActiveSupport method). `default` parameter is supported by ActiveSupport 5.0+.

In version 2.0.2, I did a fix, but it wasn't complete.

**Comment by zhandao** [comment]
2.0.3 is released.

**Comment by drjonnicholson** [comment]
👍 I was just about to do a PR to fix this, that fixes the error. Now just need to figure out whart went wront updating ours from 1.6.0

**Comment by zhandao** [comment]
@drjonnicholson Why you don't want it to traverse controllers?

**Comment by akram71093** [comment]
@zhandao Yes the server is working now. Thank you for the immediate fix.
Will try the functionality later to see if there is any other problem

**Comment by zhandao** [comment]
@akram71093 There are some breaking changes in unusual features in version 2, let me know if you have any questions.

**Comment by drjonnicholson** [comment]
@zhandao I want to traverse the controllers, but `generate_doc` doesn't do that. So I call `generate_docs` and get the spec out of the returned hash, which solved the problem.

**Comment by zhandao** [comment]
@drjonnicholson Ahh, yes!

And this issue is now closed.
